language: cpp
os: osx
osx_image: xcode11.6

addons:
  homebrew:
    packages:
    - cmake
    - qt5
    - qtkeychain
    - openssl
    casks:
    - packages

script:
     - mkdir -p build
     - cd build
     - cmake -Wno-dev -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCMAKE_INSTALL_PREFIX=~/nextcloud-desktop-client -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1 ..
     - make
