os: osx

addons:
  homebrew:
    packages:
    - cmake
    - qt5
    - qtkeychain
    casks:
    - packages

script:
     - mkdir -p build
     - cd build
     - cmake .. -DCMAKE_INSTALL_PREFIX=~/nextcloud-desktop-client -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1
     - make
