language: cpp
os: osx
osx_image: xcode11.6

env:
  global:
    - NC_BUILD_DIR=${TRAVIS_BUILD_DIR}/build
    - NC_INSTALL_DIR=${HOME}/nextcloud-desktop-client

addons:
  homebrew:
    packages:
      - cmake
      - qt5
      - qtkeychain
      - openssl
    casks:
      - packages

script:
  - mkdir -p ${NC_BUILD_DIR}
  - cd ${NC_BUILD_DIR}
  - cmake -Wno-dev -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCMAKE_INSTALL_PREFIX=${NC_INSTALL_DIR} -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1 ${TRAVIS_BUILD_DIR}
  - make
  - make install
  - bash admin/osx/create_mac.sh ${NC_INSTALL_DIR} ${NC_BUILD_DIR} "Quality Location GmbH"

before_deploy:
  - cd ${HOME}
  - tar -zcf ${TRAVIS_COMMIT}-${TRAVIS_BUILD_NUMBER}.tar.gz nextcloud-desktop-client

deploy:
  provider: releases
  api_key:
    secure: YJLyhwrQ9ww5EsuvR0lOCh2tBB1mtPZaI92yB5cRIiMgdnmQQ8K1FuxVbZrFr8FgHIsKArT7mn1NqsUippBd/DduQj8Bk5MjxfYL+jyxjVDSYJgZwRTkoGgBESsM+gjaiIfalxCOLMckzTbQbefC5/bgtKR247bQnGyRpY8+nl6p8kuApfP8Rj1ujuU74t8q+M2NCfu8YHSmO+aM5Q4EHcDegdz/CRlnX5AF/Zmmyp6pJFPanMMOGQ8d2m0tHKmmswxNiozXvTbaGT6hUyeYO2QenzUtERZPA7uwJgJH8zc3mtXkPQV62eGAmzCaTJlJvsvDlnkeZ2w7Nk+TuCvKBurWji3kik3phZe6mdHcyxY/I2uRJhtt2uhn+CYLvqlBY9N/TMKBStOCDwwKziM7aD0x6/oDJTLINcXZL9Tx4kzt2AWRimLc/mtE/0PjhPUXzgx2HUgPRkWXOMCLCoXnpWGokaNoKpnyZ/3Rj34xvrw8l5j7yltOJOIfet1PDuSARY8rJBkYF5UBSSb8Oj5VCZ8HtYSr2U014r5HC4Sofak3WzPdBCpCXIBPOBXUkTPKBQuMOujnJGuiYrHi4/m+SAGtoDhH85zRyNpFQ3UrRH23QPhYHEo+ZiryMoXGMMSoy+R8QTU7yBiUKbKo39ogtE36Cdia4cMDTRiG4dYWS50=
  file: ${HOME}/${TRAVIS_COMMIT}-${TRAVIS_BUILD_NUMBER}.tar.gz
  draft: true
  skip_cleanup: true
