language: cpp
os: osx
osx_image: xcode11.6

env:
  global:
    - NC_BUILD_DIR=$TRAVIS_BUILD_DIR/build
    - NC_INSTALL_DIR=$HOME/nextcloud-desktop-client

addons:
  artifacts:
    paths:
    - $NC_INSTALL_DIR
  homebrew:
    packages:
    - cmake
    - qt5
    - qtkeychain
    - openssl
    casks:
    - packages

script:
     - mkdir -p $NC_BUILD_DIR
     - cd $NC_BUILD_DIR
     - cmake -Wno-dev -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCMAKE_INSTALL_PREFIX=$NC_INSTALL_DIR -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1 $TRAVIS_BUILD_DIR
     - make
     - make install
     - bash admin/osx/create_mac.sh $NC_INSTALL_DIR $NC_BUILD_DIR "Quality Location GmbH"
